name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger only when a GitHub Release is published.

jobs:
  publish:
    if: github.repository == 'cognizant-ai-lab/nsflow'
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: pypi  # Match this to your configured GitHub Environment.
    permissions:
      id-token: write  # Mandatory for PyPI Trusted Publishing

    steps:
      # actions/checkout v6.0.2
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # cognizant-ai-lab/build-common 1.0.11 -- build-python-dists
      - name: Build wheel and sdist
        uses: cognizant-ai-lab/build-common/actions/build-python-dists@a70df67b0d623e56f34159de26c38989cd315d26
        with:
          python-version: '3.12'

      # pypa/gh-action-pypi-publish v1.14.0
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b

      # cognizant-ai-lab/build-common 1.0.11 -- slack-notify
      - name: Notify Slack
        if: ${{ !cancelled() }}
        uses: cognizant-ai-lab/build-common/actions/slack-notify@a70df67b0d623e56f34159de26c38989cd315d26
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
