name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger only when a GitHub Release is published.

jobs:
  publish:
    if: github.repository == 'cognizant-ai-lab/nsflow'
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: pypi  # Match this to your configured GitHub Environment.
    permissions:
      id-token: write  # Mandatory for PyPI Trusted Publishing

    steps:
      - name: Checkout code
        # actions/checkout v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python and install build tools
        # cognizant-ai-lab/build-common setup-python-env 1.0.0
        uses: cognizant-ai-lab/build-common/actions/setup-python-env@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
        with:
          python-version: '3.10'
          requirements-file: ''
          install-extras: 'build'

      - name: Build wheel and sdist
        run: python -m build

      - name: Publish to PyPI
        # pypa/gh-action-pypi-publish v1.14.0
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b

      - name: Notify Slack
        if: ${{ !cancelled() }}
        # cognizant-ai-lab/build-common slack-notify 1.0.0
        uses: cognizant-ai-lab/build-common/actions/slack-notify@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
