name: Test

on:
  push:
    branches:
      - main
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    if: github.repository == 'cognizant-ai-lab/nsflow'
    # 1.0.0
    uses: cognizant-ai-lab/build-common/.github/workflows/_python-quality-gate.yml@455db3cc40e9ed6a0fb9bbaf8188888c1ae315c2
    with:
      python-version: '3.12'
      # No lint or test steps in original workflow
      lint-command-override: 'true'
      run-shellcheck: false
      run-pytest: false
      check-readme-pypi: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


